const pages=[['dashboard','⌂','Обзор'],['products','◫','Продукты'],['recipes','◇','Рецепты'],['diary','☷','Дневник'],['progress','↗','Прогресс'],['workouts','⚡','Тренировки']];let page='dashboard',cache={},sort={key:null,dir:0};
const $=s=>document.querySelector(s),api=async(u,o)=>{const r=await fetch('/api/'+u,{headers:{'Content-Type':'application/json'},...o});const x=await r.json();if(!r.ok)throw Error(x.error||'Ошибка');return x};
$('#nav').innerHTML=pages.map(([id,ic,n])=>`<button data-page="${id}">${ic}　${n}</button>`).join('');$('#nav').onclick=e=>{if(e.target.dataset.page){page=e.target.dataset.page;sort={key:null,dir:0};render()}};$('#add').onclick=()=>openForm(page);
const fmt=n=>n==null?'—':Number(n).toLocaleString('ru-RU',{maximumFractionDigits:1}), date=v=>v?new Date(v).toLocaleDateString('ru-RU'):'—';
async function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#title').textContent=pages.find(x=>x[0]===page)[2];$('#add').style.display=page==='dashboard'?'none':'';$('#content').innerHTML='<div class="panel">Загрузка…</div>';try{if(page==='dashboard')await dashboard();else await listing()}catch(e){$('#content').innerHTML=`<div class="panel empty">${e.message}</div>`}}
async function dashboard(){const d=await api('dashboard');$('#content').innerHTML=`<div class="kpis"><div class="card"><span class="label">Продукты</span><strong>${d.products}</strong></div><div class="card"><span class="label">Рецепты</span><strong>${d.recipes}</strong></div><div class="card"><span class="label">Approved</span><strong>${d.approved}</strong></div><div class="card"><span class="label">Текущий вес</span><strong>${d.latest[0]?.weight_kg||'—'} <small>кг</small></strong></div></div><div class="panel"><h3>Самые белковые порции</h3><div class="bars">${d.top.map(x=>`<div class="bar"><span>${x.name}</span><div class="track"><i style="width:${Math.min(x.protein_per_serving_g/55*100,100)}%"></i></div><b>${fmt(x.protein_per_serving_g)} г</b></div>`).join('')}</div></div>`}
const defs={products:{cols:[['product_id','ID'],['name','Продукт'],['category','Категория'],['kcal','Ккал'],['protein_g','Белки'],['fat_g','Жиры'],['carbs_g','Углеводы'],['data_status','Статус']]},recipes:{cols:[['recipe_id','ID'],['name','Рецепт'],['category','Категория'],['version','Версия'],['status','Статус'],['kcal_per_serving','Ккал/порц.'],['protein_per_serving_g','Белок/порц.'],['cost_per_serving_rsd','Цена/порц.']]},diary:{cols:[['entry_date','Дата'],['meal_type','Прием пищи'],['name','Блюдо'],['servings','Порций'],['kcal_per_serving','Ккал/порц.'],['protein_per_serving_g','Белок/порц.']]},progress:{cols:[['measured_at','Дата'],['weight_kg','Вес'],['waist_cm','Талия'],['chest_cm','Грудь'],['hips_cm','Бедра'],['sleep_score','Сон'],['wellbeing_score','Самочувствие'],['comment','Комментарий']]},workouts:{cols:[['performed_at','Дата'],['name','Упражнение'],['muscle_group','Группа'],['working_weight','Вес'],['sets','Подходы'],['reps','Повторы'],['rir','RIR'],['machine_location','Тренажер / зал']]}};
const idLegend={B:'Breakfast · завтрак',M:'Main · основное блюдо',W:'Wrap · врап',D:'Dessert · десерт',G:'Garnish · гарнир',S:'Salad · салат',SA:'Sauce · соус',SN:'Snack · перекус',DR:'Drink · напиток'};
async function listingLegacy(){let data=await api(page);cache[page]=data;const cols=defs[page].cols;const legend=page==='recipes'?`<details class="legend"><summary>Что означают ID рецептов?</summary><div>${Object.entries(idLegend).map(([k,v])=>`<span><b>${k}-</b> ${v}</span>`).join('')}</div><p>Цифры после дефиса — последовательный номер рецепта в категории.</p></details>`:'';$('#content').innerHTML=`${legend}<div class="toolbar"><input id="search" placeholder="Поиск…"><span class="subtle">Записей: ${data.length}</span><button class="reset-sort" id="reset-sort" disabled>Сбросить сортировку</button></div><div class="panel table-panel"><table><thead><tr>${cols.map(c=>`<th><button class="sort-button" data-key="${c[0]}">${c[1]} <span></span></button></th>`).join('')}</tr></thead><tbody id="tbody"></tbody></table></div>`;let query='';const draw=()=>{let shown=data.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase()));if(sort.dir)shown=[...shown].sort((a,b)=>compare(a[sort.key],b[sort.key])*sort.dir);$('#tbody').innerHTML=shown.map(x=>`<tr ${page==='recipes'?`class="clickable" data-id="${x.recipe_id}" tabindex="0" title="Открыть состав рецепта"`:''}>${cols.map(c=>`<td class="${typeof x[c[0]]==='number'?'number':''}">${c[0]==='status'||c[0]==='data_status'?`<span class="pill">${x[c[0]]}</span>`:c[0].includes('date')||c[0].includes('_at')?date(x[c[0]]):fmtValue(x[c[0]])}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${cols.length}" class="empty">Ничего не найдено</td></tr>`;document.querySelectorAll('.sort-button').forEach(b=>b.querySelector('span').textContent=sort.key===b.dataset.key?(sort.dir===1?'↑':'↓'):'↕');$('#reset-sort').disabled=!sort.dir};draw();$('#search').oninput=e=>{query=e.target.value;draw()};document.querySelector('thead').onclick=e=>{const b=e.target.closest('.sort-button');if(!b)return;if(sort.key!==b.dataset.key)sort={key:b.dataset.key,dir:1};else if(sort.dir===1)sort.dir=-1;else sort={key:null,dir:0};draw()};$('#reset-sort').onclick=()=>{sort={key:null,dir:0};draw()};if(page==='recipes'){$('#tbody').onclick=e=>{const tr=e.target.closest('tr[data-id]');if(tr)openRecipe(tr.dataset.id)};$('#tbody').onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.id){e.preventDefault();openRecipe(e.target.dataset.id)}}}}

async function listing(){
 const data=await api(page);cache[page]=data;const cols=defs[page].cols;
 const categoryInfo={Breakfast:['Завтраки','☀'],Main:['Основные блюда','🍽'],Wrap:['Врапы','◒'],Dessert:['Десерты','✦'],Garnish:['Гарниры','◐'],Salad:['Салаты','❧'],Snack:['Перекусы','◇'],Drink:['Напитки','◉'],Sauce:['Соусы','◌']};
 const counts=data.reduce((a,x)=>(a[x.category]=(a[x.category]||0)+1,a),{});
 if(page==='recipes'&&!listing.category)listing.category='all';
 const categoryCards=page==='recipes'?`<section class="recipe-categories" aria-label="Типы рецептов"><button class="category-card all ${listing.category==='all'?'active':''}" data-category="all"><span class="category-icon">▦</span><span><b>Все рецепты</b><small>Полный каталог</small></span><strong>${data.length}</strong></button>${Object.entries(categoryInfo).filter(([key])=>counts[key]).map(([key,[name,icon]])=>`<button class="category-card category-${key.toLowerCase()} ${listing.category===key?'active':''}" data-category="${key}"><span class="category-icon">${icon}</span><span><b>${name}</b><small>${key}</small></span><strong>${counts[key]}</strong></button>`).join('')}</section>`:'';
 const legend=page==='recipes'?`<details class="legend"><summary>Что означают ID рецептов?</summary><div>${Object.entries(idLegend).map(([k,v])=>`<span><b>${k}-</b> ${v}</span>`).join('')}</div><p>Цифры после дефиса — последовательный номер рецепта в категории.</p></details>`:'';
 const selectedName=listing.category==='all'?'Все рецепты':categoryInfo[listing.category]?.[0]||listing.category;
 $('#content').innerHTML=`${categoryCards}${legend}<div class="toolbar"><input id="search" placeholder="Поиск…"><span class="subtle" id="records-count"></span><button class="reset-sort" id="reset-sort" disabled>Сбросить сортировку</button></div><div class="panel table-panel"><div class="table-heading"><div><span class="eyebrow">КАТАЛОГ</span><h3 id="table-category">${page==='recipes'?selectedName:pages.find(x=>x[0]===page)[2]}</h3></div></div><table><thead><tr>${cols.map(c=>`<th><button class="sort-button" data-key="${c[0]}">${c[1]} <span></span></button></th>`).join('')}</tr></thead><tbody id="tbody"></tbody></table></div>`;
 let query='';
 const draw=()=>{let shown=data.filter(x=>(page!=='recipes'||listing.category==='all'||x.category===listing.category)&&JSON.stringify(x).toLowerCase().includes(query.toLowerCase()));if(sort.dir)shown=[...shown].sort((a,b)=>compare(a[sort.key],b[sort.key])*sort.dir);$('#records-count').textContent=`Записей: ${shown.length}`;$('#tbody').innerHTML=shown.map(x=>`<tr ${page==='recipes'?`class="clickable" data-id="${x.recipe_id}" tabindex="0" title="Открыть состав рецепта"`:''}>${cols.map(c=>`<td class="${typeof x[c[0]]==='number'?'number':''}">${c[0]==='status'||c[0]==='data_status'?`<span class="pill">${x[c[0]]}</span>`:c[0].includes('date')||c[0].includes('_at')?date(x[c[0]]):fmtValue(x[c[0]])}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${cols.length}" class="empty">Ничего не найдено</td></tr>`;document.querySelectorAll('.sort-button').forEach(b=>b.querySelector('span').textContent=sort.key===b.dataset.key?(sort.dir===1?'↑':'↓'):'↕');$('#reset-sort').disabled=!sort.dir};
 draw();$('#search').oninput=e=>{query=e.target.value;draw()};document.querySelector('thead').onclick=e=>{const b=e.target.closest('.sort-button');if(!b)return;if(sort.key!==b.dataset.key)sort={key:b.dataset.key,dir:1};else if(sort.dir===1)sort.dir=-1;else sort={key:null,dir:0};draw()};$('#reset-sort').onclick=()=>{sort={key:null,dir:0};draw()};
 if(page==='recipes'){document.querySelector('.recipe-categories').onclick=e=>{const card=e.target.closest('.category-card');if(!card)return;listing.category=card.dataset.category;sort={key:null,dir:0};document.querySelectorAll('.category-card').forEach(x=>x.classList.toggle('active',x===card));$('#table-category').textContent=listing.category==='all'?'Все рецепты':categoryInfo[listing.category][0];draw();document.querySelector('.table-panel').scrollIntoView({behavior:'smooth',block:'start'})};$('#tbody').onclick=e=>{const tr=e.target.closest('tr[data-id]');if(tr)openRecipe(tr.dataset.id)};$('#tbody').onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.id){e.preventDefault();openRecipe(e.target.dataset.id)}}}
}
function compare(a,b){if(a==null&&b==null)return 0;if(a==null)return 1;if(b==null)return-1;if(typeof a==='number'&&typeof b==='number')return a-b;const da=Date.parse(a),db=Date.parse(b);if(!Number.isNaN(da)&&!Number.isNaN(db)&&String(a).match(/^\d{4}-/))return da-db;return String(a).localeCompare(String(b),'ru',{numeric:true,sensitivity:'base'})}
function fmtValue(v){return typeof v==='number'?fmt(v):(v??'—')}
async function openRecipe(id){const d=await api('recipes/'+id),r=d.recipe[0],m=$('#recipe-modal');if(!r)return;$('#recipe-title').textContent=r.name;$('#recipe-meta').textContent=`${r.recipe_id} · ${r.category}${r.subcategory?' / '+r.subcategory:''} · v${r.version} · ${r.servings} порц.`;$('#recipe-body').innerHTML=`<div class="recipe-kpis"><div><span>На порцию</span><b>${fmt(r.kcal_per_serving)} ккал</b></div><div><span>Белки</span><b>${fmt(r.protein_per_serving_g)} г</b></div><div><span>Жиры</span><b>${fmt(r.fat_per_serving_g)} г</b></div><div><span>Углеводы</span><b>${fmt(r.carbs_per_serving_g)} г</b></div></div><h3>Состав всего рецепта</h3><div class="recipe-table"><table><thead><tr><th>Продукт</th><th>Количество</th><th>Ккал</th><th>Белки</th><th>Жиры</th><th>Углеводы</th></tr></thead><tbody>${d.ingredients.map(i=>`<tr><td><b>${i.name}</b><small>${i.portion_description||i.product_id}</small></td><td class="number">${fmt(i.quantity)} ${i.unit}</td><td class="number">${fmt(i.kcal)}</td><td class="number">${fmt(i.protein_g)}</td><td class="number">${fmt(i.fat_g)}</td><td class="number">${fmt(i.carbs_g)}</td></tr>`).join('')}</tbody></table></div>`;m.showModal()}
$('#close-recipe').onclick=()=>$('#recipe-modal').close();$('#recipe-modal').onclick=e=>{if(e.target===$('#recipe-modal'))$('#recipe-modal').close()};
const field=(name,label,type='text',extra='')=>`<div class="field"><label>${label}</label><input name="${name}" type="${type}" ${extra}></div>`, select=(name,label,opts)=>`<div class="field"><label>${label}</label><select name="${name}">${opts.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select></div>`;
async function openForm(kind){const m=$('#modal'),f=$('#fields');$('#form-error').textContent='';$('#modal-title').textContent='Добавить: '+pages.find(x=>x[0]===kind)[2].toLowerCase();
 if(kind==='products')f.innerHTML=`<div class="grid">${field('product_id','ID (например P-036)','text','required')}${field('name','Название','text','required')}${field('category','Категория')}${select('unit','Единица',[['г','г'],['мл','мл'],['шт','шт'],['бут.','бут.']])}${field('package_price_rsd','Цена упаковки','number','step="0.01"')}${field('package_size','Размер упаковки','number','step="0.01"')}${field('price_per_100_or_unit_rsd','Цена за 100 г / единицу','number','step="0.01"')}${field('kcal','Ккал','number','step="0.01" required')}${field('protein_g','Белки','number','step="0.01" required')}${field('fat_g','Жиры','number','step="0.01" required')}${field('carbs_g','Углеводы','number','step="0.01" required')}${select('data_status','Статус данных',[['Подтверждено','Подтверждено'],['Оценка','Оценка']])}${field('note','Примечание')}</div>`;
 if(kind==='recipes'){const ps=await api('products');f.innerHTML=`<div class="grid">${field('recipe_id','ID (M-006, W-004…)','text','required')}${field('name','Название','text','required')}${select('category','Категория',[['Main','Main'],['Breakfast','Breakfast'],['Wrap','Wrap'],['Dessert','Dessert'],['Garnish','Garnish'],['Salad','Salad'],['Snack','Snack'],['Drink','Drink']])}${field('subcategory','Подкатегория')}${field('version','Версия','text','value="1.0"')}${select('status','Статус',[['Draft','Draft'],['Testing','Testing'],['Approved','Approved'],['Archived','Archived']])}${field('servings','Количество порций','number','min="1" value="1" required')}${field('tags','Теги')}</div><div class="field full" style="margin-top:16px"><label>Ингредиенты</label><div id="ingredients"></div><button type="button" id="add-ing">＋ ингредиент</button></div>`;const add=()=>{$('#ingredients').insertAdjacentHTML('beforeend',`<div class="ingredient-row"><select class="ip">${ps.map(p=>`<option value="${p.product_id}" data-unit="${p.unit}">${p.name}</option>`)}</select><input class="iq" type="number" step="0.01" placeholder="Количество" required><button type="button" onclick="this.parentElement.remove()">×</button></div>`)};$('#add-ing').onclick=add;add()}
 if(kind==='diary'){const rs=await api('recipes');f.innerHTML=`<div class="grid">${field('entry_date','Дата','date','required')}${select('meal_type','Прием пищи',[['Завтрак','Завтрак'],['Обед','Обед'],['Ужин','Ужин'],['Перекус','Перекус'],['Напиток','Напиток']])}${select('recipe_id','Блюдо',rs.map(r=>[r.recipe_id,r.name]))}${field('servings','Порций','number','step="0.25" value="1" required')}${field('comment','Комментарий')}</div>`}
 if(kind==='progress')f.innerHTML=`<div class="grid">${field('measured_at','Дата','date','required')}${field('weight_kg','Вес, кг','number','step="0.1"')}${field('waist_cm','Талия, см','number','step="0.1"')}${field('chest_cm','Грудь, см','number','step="0.1"')}${field('hips_cm','Бедра, см','number','step="0.1"')}${field('sleep_score','Сон (1–5)','number','min="1" max="5"')}${field('wellbeing_score','Самочувствие (1–5)','number','min="1" max="5"')}${field('comment','Комментарий')}</div>`;
 if(kind==='workouts'){const es=await api('exercises');f.innerHTML=`<div class="grid">${field('performed_at','Дата','date','required')}${select('exercise_id','Упражнение',es.map(e=>[e.exercise_id,e.name]))}${field('working_weight','Рабочий вес','number','step="0.5"')}${field('sets','Подходы','number','value="3"')}${field('reps','Повторы','number','value="12"')}${field('rir','RIR','text','value="0–2"')}${field('machine_location','Тренажер / филиал')}${field('comment','Комментарий')}</div>`}
 m.showModal();$('#form').onsubmit=async e=>{e.preventDefault();if(e.submitter?.value==='cancel'){m.close();return}const data=Object.fromEntries(new FormData(e.target));if(kind==='recipes')data.ingredients=[...document.querySelectorAll('.ingredient-row')].map(r=>({product_id:r.querySelector('.ip').value,quantity:r.querySelector('.iq').value,unit:r.querySelector('.ip').selectedOptions[0].dataset.unit}));try{await api(kind,{method:'POST',body:JSON.stringify(data)});m.close();render()}catch(err){$('#form-error').textContent=err.message}}}
render();
